### PR TITLE
DM-33505: Convert gbdes build to cmake

### PR DESCRIPTION
**Pull request by cmsaunders**

### CODE REVIEW

**Comment by mwittgen** [comment]
I wonder why there are 135 files changes compared to the target branch. Also the forked branch of
[gaiadr2](https://github.com/cmsaunders/gbdes/tree/gaiadr2) is 45 commits ahead of the original.

**Comment by mwittgen** [comment]
The PR title should read cmake not make.

**Comment by mwittgen** [comment]
Comparing `gbernstein:gaiadr2` and `cmsaunders:gaiadr2` looks mainly like formatting differences.
Is the idea to diverge with these two packages so the upstream doesn't matter any more?

**Comment by mwittgen** [comment]
Looks OK to me, but since this is becoming its own package with little resemblance of the upstream `gbdes`, the C++ code could be cleaned up in the next.

**Comment by cmsaunders** [comment]
Yes, this version of the code should be identical to the user. The changes have been in refactoring so that it can be wrapped with pybind11 and making the c++ more memory safe (which is also essential for the pybind11 wrapping). This is where the 45 commits come from with work by Jim Bosch and myself. There are so many files in this commit because this includes changing the packages `astrometry`, `gbutil`, etc. from dependencies to subdirectories in order to have an easier time building `gbdes` in the LSST stack.

Some work has already been done to clean up the c++, like the memory-safety work mentioned above. There are a few tickets covering further changes to be made.

**Pull request merged**
